CREATE DATABASE FilmesBD;
GO

USE FilmesBD;
GO

CREATE TABLE Genero(
	IdGenero INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Filme(
	IdFilme INT PRIMARY KEY IDENTITY,
	Imagem VARCHAR(100),
	Titulo VARCHAR(100) NOT NULL,
	IdGenero INT FOREIGN KEY REFERENCES Genero(IdGenero)
);
GO

CREATE TABLE Usuario(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(256) UNIQUE NOT NULL,
	Senha VARCHAR(60) NOT NULL
);